"""Adicionada a tabela cartoes

Revision ID: fb0205e6febf
Revises: 
Create Date: 2024-11-02 23:18:07.215506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0205e6febf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('titular_cartao', sa.String(), nullable=False),
    sa.Column('cpf_titular', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'CANCELADO', 'BLOQUEADO', 'ENVIADO', 'EXPIRADO', 'EM_ANALISE', 'BLACKLISTED', name='statusenum'), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('saldo', sa.Double(), nullable=False),
    sa.Column('numero_cartao', sa.String(), nullable=False),
    sa.Column('expiracao', sa.Date(), nullable=False),
    sa.Column('cvv', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cartao'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_cartoes_cpf_titular'), 'cartoes', ['cpf_titular'], unique=False)
    op.create_index(op.f('ix_cartoes_endereco'), 'cartoes', ['endereco'], unique=False)
    op.create_index(op.f('ix_cartoes_id'), 'cartoes', ['id'], unique=False)
    op.create_index(op.f('ix_cartoes_titular_cartao'), 'cartoes', ['titular_cartao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartoes_titular_cartao'), table_name='cartoes')
    op.drop_index(op.f('ix_cartoes_id'), table_name='cartoes')
    op.drop_index(op.f('ix_cartoes_endereco'), table_name='cartoes')
    op.drop_index(op.f('ix_cartoes_cpf_titular'), table_name='cartoes')
    op.drop_table('cartoes')
    # ### end Alembic commands ###
