services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - postgres_test
      - pgadmin
    command: sh -c "poetry run python main.py"

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql_test/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_test_data: